package Akanoid;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.Beans;
import java.io.IOException;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import org.jdesktop.layout.GroupLayout;
import org.jdesktop.layout.LayoutStyle;

/**
 *
 * @author Luk
 */
public class Main extends javax.swing.JFrame {

    FLC flc = new FLC();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        flc.initFuzzySets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new JTabbedPane();
        gamePlay2 = new GamePlay();
        jPanel1 = new JPanel();
        jButton1 = new JButton();
        tfZeroInU = new JTextField();
        tfZeroInX = new JTextField();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        ResourceBundle bundle = ResourceBundle.getBundle("Akanoid/Bundle"); // NOI18N
        setTitle(bundle.getString("Main.title")); // NOI18N
        setLocationByPlatform(true);
        setMaximumSize(new Dimension(750, 650));
        setPreferredSize(new Dimension(730, 630));
        setResizable(false);
        setSize(new Dimension(703, 603));

        jTabbedPane1.setFocusable(false);

        GroupLayout gamePlay2Layout = new GroupLayout(gamePlay2);
        gamePlay2.setLayout(gamePlay2Layout);
        gamePlay2Layout.setHorizontalGroup(gamePlay2Layout.createParallelGroup(GroupLayout.LEADING)
            .add(0, 700, Short.MAX_VALUE)
        );
        gamePlay2Layout.setVerticalGroup(gamePlay2Layout.createParallelGroup(GroupLayout.LEADING)
            .add(0, 575, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(bundle.getString("Main.gamePlay2.TabConstraints.tabTitle"), gamePlay2); // NOI18N

        jButton1.setText(bundle.getString("Main.jButton1.text")); // NOI18N
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfZeroInU.setText(bundle.getString("Main.tfZeroInU.text")); // NOI18N
        tfZeroInU.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                tfZeroInUMouseClicked(evt);
            }
        });
        tfZeroInU.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                tfZeroInUActionPerformed(evt);
            }
        });

        tfZeroInX.setText(bundle.getString("Main.tfZeroInX.text")); // NOI18N
        tfZeroInX.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                tfZeroInXMouseClicked(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(GroupLayout.LEADING)
                    .add(tfZeroInU)
                    .add(tfZeroInX, GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE))
                .addPreferredGap(LayoutStyle.RELATED)
                .add(jButton1, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                .add(4, 4, 4))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(13, 13, 13)
                        .add(tfZeroInU, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.RELATED)
                        .add(tfZeroInX, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(29, 29, 29)
                        .add(jButton1)))
                .addContainerGap(516, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(bundle.getString("Main.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jTabbedPane1.setSelectedComponent(gamePlay2);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.LEADING)
            .add(jTabbedPane1)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.LEADING)
            .add(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        flc.initZero(tfZeroInU, tfZeroInX);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfZeroInUMouseClicked(MouseEvent evt) {//GEN-FIRST:event_tfZeroInUMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tfZeroInUMouseClicked

    private void tfZeroInXMouseClicked(MouseEvent evt) {//GEN-FIRST:event_tfZeroInXMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tfZeroInXMouseClicked

    private void tfZeroInUActionPerformed(ActionEvent evt) {//GEN-FIRST:event_tfZeroInUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfZeroInUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GamePlay gamePlay2;
    private JButton jButton1;
    private JPanel jPanel1;
    private JTabbedPane jTabbedPane1;
    private JTextField tfZeroInU;
    private JTextField tfZeroInX;
    // End of variables declaration//GEN-END:variables
}
